import 'package:book/model/topic.dart';
import 'package:book/model/sub_topic.dart';

List<Topic> topics = [
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Aerospace-Equipment', topicID: null),
      SubTopic(title: 'Automation', topicID: null),
      SubTopic(title: 'Communication-Telecommunications', topicID: null),
      SubTopic(title: 'Communication', topicID: null),
      SubTopic(title: 'Construction', topicID: null),
      SubTopic(title: 'Construction:CementIndustry', topicID: null),
      SubTopic(
          title: 'Construction:Rennovation-And-Interior-Design:Saunas',
          topicID: null),
      SubTopic(
          title: 'Construction-Renovation-And-Interior-Design', topicID: null),
      SubTopic(
          title: 'Construction:Ventilation-And-Air-Conditioning',
          topicID: null),
      SubTopic(title: 'Electroinics:Electronics', topicID: null),
      SubTopic(title: 'Electronics:Fiber-Optics', topicID: null),
      SubTopic(title: 'Electronics:Hardware', topicID: null),
      SubTopic(title: 'Electronics:Home-Electronics', topicID: null),
      SubTopic(title: 'Electronics:Microprocessor-Technology', topicID: null),
      SubTopic(title: 'Electronics:Radio', topicID: null),
      SubTopic(title: ' Electronics:Robotics', topicID: null),
      SubTopic(title: 'Electronics:Signal-Processing', topicID: null),
      SubTopic(title: 'Electronics:Telecommunications', topicID: null),
      SubTopic(title: 'Electronics:TV. Video', topicID: null),
      SubTopic(title: 'Electronics:VlSI', topicID: null),
      SubTopic(title: 'Electronics', topicID: null),
      SubTopic(title: 'Energy:Renewable Energy', topicID: null),
      SubTopic(title: 'Energy', topicID: null),
      SubTopic(title: 'Food-Manufacturing', topicID: null),
      SubTopic(title: 'Fuel-Technology', topicID: null),
      SubTopic(title: 'Heat', topicID: null),
      SubTopic(title: 'Industrial-Equipment-And-Technology', topicID: null),
      SubTopic(title: 'Industry:Metallurgy', topicID: null),
      SubTopic(title: 'Instrument', topicID: null),
      SubTopic(title: 'Light-Industry', topicID: null),
      SubTopic(title: 'Materials', topicID: null),
      SubTopic(title: 'Mechanical-Engineering', topicID: null),
      SubTopic(title: 'Metallurgy', topicID: null),
      SubTopic(title: 'Metrology', topicID: null),
      SubTopic(title: 'Military-Equipment:Weapon', topicID: null),
      SubTopic(title: 'Military-Equipment', topicID: null),
      SubTopic(title: 'Missiles', topicID: null),
      SubTopic(title: 'Nanotechnology', topicID: null),
      SubTopic(title: 'Oil-And-Gas-Technology:pipelines', topicID: null),
      SubTopic(title: 'Oil-And-Gas-Technologies', topicID: null),
      SubTopic(title: 'Patent-Bussiness-Ingenuity.Innovation', topicID: null),
      SubTopic(title: 'Publishing', topicID: null),
      SubTopic(title: 'Regulatory-Literature', topicID: null),
      SubTopic(title: 'Safety-And-Security', topicID: null),
      SubTopic(title: 'Space-Science', topicID: null),
      SubTopic(title: 'Transport', topicID: null),
      SubTopic(title: 'Transportaion:Aviation', topicID: null),
      SubTopic(title: 'Transportation:Cars,Motorcycles', topicID: null),
      SubTopic(title: 'Transportation:Rail', topicID: null),
      SubTopic(title: 'Transporation:Ships', topicID: null),
      SubTopic(title: 'Water-Treatment', topicID: null),
    ],
    topic: 'Engineering/Tchnology',
    topicId: 'topicid210',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Cinema', topicID: null),
      SubTopic(title: 'Design:Architecture', topicID: null),
      SubTopic(title: 'Graphic-Arts', topicID: null),
      SubTopic(title: 'Music', topicID: null),
      SubTopic(title: 'Music-Guitar', topicID: null),
      SubTopic(title: 'Photo', topicID: null),
    ],
    topic: "Art",
    topicId: 'topicid57',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Anthropology', topicID: null),
      SubTopic(title: 'Anthropology:Evolution', topicID: null),
      SubTopic(title: 'Biostatistics', topicID: null),
      SubTopic(title: 'Biotechnology', topicID: null),
      SubTopic(title: 'Biophysics', topicID: null),
      SubTopic(title: 'Biochemistry', topicID: null),
      SubTopic(title: 'Biochemistry:Enologist', topicID: null),
      SubTopic(title: 'Ecology', topicID: null),
      SubTopic(title: 'Estestvoznananie', topicID: null),
      SubTopic(title: 'Genetics', topicID: null),
      SubTopic(title: 'Microbiology', topicID: null),
      SubTopic(title: 'Molecular', topicID: null),
      SubTopic(title: 'Molecular:Bioinformations', topicID: null),
      SubTopic(title: 'Plants:Agriculture-And-Forestry', topicID: null),
      SubTopic(title: 'Virology', topicID: null),
      SubTopic(title: 'Zoology', topicID: null),
      SubTopic(title: 'Zoology:Paleontology', topicID: null),
      SubTopic(title: 'Zoology:Fish', topicID: null),
    ],
    topic: 'biology',
    topicId: 'topicid12',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Accounting', topicID: null),
      SubTopic(title: 'E-Commerce', topicID: null),
      SubTopic(title: 'Logistics', topicID: null),
      SubTopic(title: 'Management', topicID: null),
      SubTopic(title: 'Marketing', topicID: null),
      SubTopic(title: 'Marketing:Advertising', topicID: null),
      SubTopic(title: 'Management:Project-Management', topicID: null),
      SubTopic(title: 'MLM', topicID: null),
      SubTopic(title: 'Responsiblity-And-Business-Ethics', topicID: null),
      SubTopic(title: 'Trading', topicID: null),
    ],
    topic: 'business',
    topicId: 'topicid1',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Analytical-Chemistry', topicID: null),
      SubTopic(title: 'Chemical', topicID: null),
      SubTopic(title: 'Inorganic-Chemistry', topicID: null),
      SubTopic(title: 'Materials', topicID: null),
      SubTopic(title: 'Organic-Chemistry', topicID: null),
      SubTopic(title: 'Pyrotechnics-And-Explosives', topicID: null),
      SubTopic(title: 'Pharmacology', topicID: null),
      SubTopic(title: 'Physical-Chemistry', topicID: null),
    ],
    topic: 'Chemistry',
    topicId: 'topicid296',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Algorithms-And-Data-Structure', topicID: null),
      SubTopic(
          title: 'Algorithms-And-Data-Structure:Cryptography', topicID: null),
      SubTopic(
          title: 'Algorithms-And-Data-Structure:Image-Processing',
          topicID: null),
      SubTopic(
          title: 'Algorithms-And-Data-Structure:Pattern-Recognition',
          topicID: null),
      SubTopic(title: 'Cybernetics', topicID: null),
      SubTopic(title: 'Cybernetics:ArtificialIntelligence', topicID: null),
      SubTopic(title: 'Cryptography', topicID: null),
      SubTopic(title: 'Database', topicID: null),
      SubTopic(title: 'Information-Systems', topicID: null),
      SubTopic(title: 'Information-System:EC-Business', topicID: null),
      SubTopic(title: 'Lecture,Monographs', topicID: null),
      SubTopic(title: 'Media', topicID: null),
      SubTopic(title: 'Networking', topicID: null),
      SubTopic(title: 'Networking:Internet', topicID: null),
      SubTopic(title: 'Opreting-Systems', topicID: null),
      SubTopic(title: ' Orgnization-And-Data-Processing', topicID: null),
      SubTopic(title: 'Programming', topicID: null),
      SubTopic(title: 'Programming:Libraries-API', topicID: null),
      SubTopic(title: 'Programming:Games', topicID: null),
      SubTopic(title: 'Programming:Compilers', topicID: null),
      SubTopic(title: 'Programming:Modeling-Language', topicID: null),
      SubTopic(title: 'Programming:Programming-Language', topicID: null),
      SubTopic(title: 'Programming:TeX,LaTeX', topicID: null),
      SubTopic(title: 'Security', topicID: null),
      SubTopic(title: 'Software:Office-Software', topicID: null),
      SubTopic(title: 'Software:Adobe-Products', topicID: null),
      SubTopic(title: 'Software:Macromedia-Products', topicID: null),
      SubTopic(title: 'Software:CAD', topicID: null),
      SubTopic(title: 'Software:Systems:Scientific-Computing', topicID: null),
      SubTopic(title: 'System-Administration', topicID: null),
      SubTopic(title: 'Web-Design', topicID: null),
    ],
    topic: 'computer',
    topicId: 'topicid69',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Geodesy.-Cartoraphy', topicID: null),
      SubTopic(title: 'Local-History', topicID: null),
      SubTopic(title: 'Local-History:Tourism', topicID: null),
      SubTopic(title: 'Meterology,Climatology', topicID: null),
      SubTopic(title: 'Russsia', topicID: null),
    ],
    topic: 'geography',
    topicId: 'topicid32',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Gidrogeology', topicID: null),
      SubTopic(title: 'Mining ', topicID: null),
    ],
    topic: 'geology',
    topicId: 'topicid38',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Econometrics', topicID: null),
      SubTopic(title: 'Investing', topicID: null),
      SubTopic(title: 'Markets', topicID: null),
      SubTopic(title: 'Mathhematical-Economics', topicID: null),
      SubTopic(title: 'Popular', topicID: null),
    ],
    topic: 'economy',
    topicId: 'topicid305',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Elementary', topicID: null),
      SubTopic(title: 'International-Conference-And-Symposiums', topicID: null),
      SubTopic(title: 'Self-Help-Book', topicID: null),
      SubTopic(title: 'Theses-Abstracts ', topicID: null),
    ],
    topic: 'education',
    topicId: 'topicid183',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Criminology,Forensic-Science', topicID: null),
      SubTopic(title: 'Criminology:Court-Examination', topicID: null),
      SubTopic(title: 'Law ', topicID: null),
    ],
    topic: 'jurisrudence',
    topicId: 'topicid324',
  ),
  Topic(
    subtopic: <SubTopic>[
      SubTopic(title: 'Aquaria', topicID: null),
      SubTopic(title: 'Astrology', topicID: null),
      SubTopic(title: 'Beauty,Image', topicID: null),
      SubTopic(title: 'Benefits-Homebrew', topicID: null),
      SubTopic(title: 'Collecting', topicID: null),
      SubTopic(title: 'Cooking', topicID: null),
      SubTopic(title: 'Fashion,Jewelry', topicID: null),
      SubTopic(title: ' Game:Bord-Game', topicID: null),
      SubTopic(title: 'Game:Chess', topicID: null),
      SubTopic(title: 'Garden,garden', topicID: null),
      SubTopic(title: 'Handicraft', topicID: null),
      SubTopic(title: 'Handicraft:Cutting-And-Sewing', topicID: null),
      SubTopic(title: 'Hunting-And-Game-Management', topicID: null),
      SubTopic(title: 'Pet', topicID: null),
      SubTopic(title: 'Professions-And-Trades', topicID: null),
    ],
    topic: 'housekeeping-leisure',
    topicId: 'topicid41',
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'history',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'Linguistics',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'Litrature',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'mathamatics',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'medicine',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'other-social-science',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'physics',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'physical-Education-and-sport',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'psychology',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'religion',
    topicId: null,
  ),
  Topic(
    subtopic: <SubTopic>[SubTopic(title: null, topicID: null)],
    topic: 'science(Genral)',
    topicId: null,
  ),
];

List<Topic> get getTopics {
  return List.from(topics);
}
